stages:
  - capture
  - build
  - deploy

variables:
  BUILD_NUMBER: $CI_PIPELINE_IID

# Job: Capture the build number as an artifact
capture-build-number:
  stage: capture
  script:
    - echo $BUILD_NUMBER > build_number.txt
  artifacts:
    paths:
      - build_number.txt

# Job: Build and push Docker image for the result microservice
build-and-push-docker-image-result:
  image: docker:20.10.7
  services:
    - docker:dind
  stage: build
  script:
    - echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t $DOCKER_USERNAME/result:${BUILD_NUMBER} ./result
    - docker images $DOCKER_USERNAME/result:${BUILD_NUMBER}
    - docker push $DOCKER_USERNAME/result:${BUILD_NUMBER}
  only:
    refs:
      - branches
    changes:
      - result/**

# Job: Update deployment file with new Docker image tag for the result microservice
update-deployment-file-result:
  stage: deploy
  environment:
    name: production
  script:
    - git config user.email "ubeujumv@gmail.com"
    - git config user.name "Ubeujum Valentino"
    - cat artifacts/build_number.txt | xargs read -r IMAGE_TAG
    - sed -i "s|image: uvalentino/result:[^ ]*|image: uvalentino/result:${IMAGE_TAG}|g" manifest/result-deployment.yaml
    - git add manifest/result-deployment.yaml
    - git commit -m "Update result image to version ${IMAGE_TAG}"
    - git push https://gitlab-ci-token:$CI_JOB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:main
  needs:
    - build-and-push-docker-image-result
    - capture-build-number

# Job: Build and push Docker image for the vote microservice
build-and-push-docker-image-vote:
  image: docker:20.10.7
  services:
    - docker:dind
  stage: build
  script:
    - echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t $DOCKER_USERNAME/vote:${BUILD_NUMBER} ./vote
    - docker images $DOCKER_USERNAME/vote:${BUILD_NUMBER}
    - docker push $DOCKER_USERNAME/vote:${BUILD_NUMBER}
  only:
    refs:
      - branches
    changes:
      - vote/**

# Job: Update deployment file with new Docker image tag for the vote microservice
update-deployment-file-vote:
  stage: deploy
  environment:
    name: production
  script:
    - git config user.email "ubeujumv@gmail.com"
    - git config user.name "Ubeujum Valentino"
    - cat artifacts/build_number.txt | xargs read -r IMAGE_TAG
    - sed -i "s|image: uvalentino/vote:[^ ]*|image: uvalentino/vote:${IMAGE_TAG}|g" manifest/vote-deployment.yaml
    - git add manifest/vote-deployment.yaml
    - git commit -m "Update vote image to version ${IMAGE_TAG}"
    - git push https://gitlab-ci-token:$CI_JOB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:main
  needs:
    - build-and-push-docker-image-vote
    - capture-build-number

# Job: Build and push Docker image for the worker microservice
build-and-push-docker-image-worker:
  image: docker:20.10.7
  services:
    - docker:dind
  stage: build
  script:
    - echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t $DOCKER_USERNAME/worker:${BUILD_NUMBER} ./worker
    - docker images $DOCKER_USERNAME/worker:${BUILD_NUMBER}
    - docker push $DOCKER_USERNAME/worker:${BUILD_NUMBER}
  only:
    refs:
      - branches
    changes:
      - worker/**

# Job: Update deployment file with new Docker image tag for the worker microservice
update-deployment-file-worker:
  stage: deploy
  environment:
    name: production
  script:
    - git config user.email "ubeujumv@gmail.com"
    - git config user.name "Ubeujum Valentino"
    - cat artifacts/build_number.txt | xargs read -r IMAGE_TAG
    - sed -i "s|image: uvalentino/worker:[^ ]*|image: uvalentino/worker:${IMAGE_TAG}|g" manifest/worker-deployment.yaml
    - git add manifest/worker-deployment.yaml
    - git commit -m "Update worker image to version ${IMAGE_TAG}"
    - git push https://gitlab-ci-token:$CI_JOB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:main
  needs:
    - build-and-push-docker-image-worker
    - capture-build-number